### ISSUE TITLE
the question

### ISSUE THREAD

**Issue by jwdnjwdn** [4rdhendu/FIML#1]
Thank you for your code about meta-learning.
When I run the code,  I meet the question about the  'AttributeError: 'Namespace' object has no attribute 'luke_warm''.I can't solve this question,could you tell the how to solve it?

**Comment by 4rdhendu** [comment]
Can you tell me the exact place in the code where it occurs?

**Comment by jwdnjwdn** [comment]
In the train.py.  sound like 374 line
